url: https://nyc-climate-change.now.sh
title: Understanding NYC’s Boldest Climate Change Law
description: A data story about Local Law 97, requiring large buildings, which contribute 1/3 of NYC’s annual greenhouse gas emissions, to meet new emissions limits. Find out why this law matters and who’s exempt.
og_image: assets/og_image.png
twitter_image: assets/twitter_card.png
byline: By Katherine Huang and Charles Hatfield